apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: mulmul
build:
  artifacts:
  - image: services-firehose
    context: services/firehose
    docker:
      dockerfile: Dockerfile
deploy:
  helm:
    hooks:
      before:
        - host:
            command: ["bash", "-c", 
              "(kubectl get namespace risingwave &> /dev/null || kubectl create namespace risingwave) && 
               (kubectl get namespace kafka &> /dev/null || kubectl create namespace kafka) && 
               (kubectl get namespace kubernetes-dashboard &> /dev/null || kubectl create namespace kubernetes-dashboard) &&
               (kubectl get crd gateways.gateway.networking.k8s.io &> /dev/null ||
               # kubectl kustomize 'github.com/kubernetes-sigs/gateway-api/config/crd/experimental?ref=v1.0.0' | kubectl apply -f -;) &&
               # istioctl install --set profile=ambient --set values.cni.cniNetnsDir=/run/netns --skip-confirmation"
              ]
            os: [darwin, linux]
    releases:
      - name: kubernetes-dashboard
        repo: https://kubernetes.github.io/dashboard
        remoteChart: kubernetes-dashboard
        setValues:
          extraArgs:
            - --enable-skip-login
            - --enable-insecure-login
          rbac.clusterReadOnlyRole: true
      # - name: kiali
      #   repo: https://kiali.org/helm-charts
      #   remoteChart: kiali-server
      #   namespace: istio-system
      #   setValues:
      #     auth.strategy: anonymous
      - name: risingwave
        repo: https://risingwavelabs.github.io/helm-charts/
        remoteChart: risingwave
        namespace: risingwave
        setValues:
          auth:
            rootUser: admin
            rootPassword: admin
      - name: kafka
        repo: https://charts.bitnami.com/bitnami
        remoteChart: kafka
        namespace: kafka
  kubectl:
    manifests:
    - services/firehose/deployment.yaml
    - https://raw.githubusercontent.com/istio/istio/release-1.20/samples/addons/prometheus.yaml
    - https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.6.4/components.yaml

